# Proxy Configuration in TOML
# Active channel to use
model_provider = "difu"

[model_providers.difu]
base_url = "https://df.dawnloadai.com:9888/v1"
api_keys = [
    "sk-df2-FUoWaErS8yuVXah-VxzYKVWcQRf93kc6zCwVjIlbt-k"
]
model = "MiniMax-M2.7-highspeed"



[model_providers.sunge]
base_url = "https://sun.meowai.net/v1"
api_keys = [
    "sk-Vq0cJbJnjYPX6oFpI1htxxBZUricumoWA9Mv1g8HZ6P525fu"
]
model = "gemini-3-flash"

[model_providers.mimo_cn]
base_url = "https://token-plan-cn.xiaomimimo.com/v1"
api_keys = [
    "tp-cim42h3bab5r5276hlrtw4ml1erzkewk52byjdekulwpfhgw",
    
]
model = "mimo-v2.5-pro"

[model_providers.mimo_sgp]
base_url = "https://token-plan-sgp.xiaomimimo.com/v1"
api_keys = [
    "tp-ss8w8aykyfk830llqc48le6sn1sypitf80b5g8b1wqe8swfl"
    
]
model = "mimo-v2.5-pro"


 # proxy/config.toml
[model_mapping]
"gpt-5.5" = "gemini-3.1-pro"
"gpt-5.4" = "gemini-3-flash"
"gpt-5.4-mini" = "gpt-5.4-mini"